require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/clients", type: :request do
  let(:valid_attributes) do
    {
      name: "New Client"
    }
  end

  let(:invalid_attributes) do
    {
      name: ""
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      create(:client)
      get api_clients_url
      
      expect(response).to be_successful
      json = JSON.parse(response.body)
      expect(json["status"]).to eq("success")
      expect(json["clients"]).to be_present
    end
  end

  describe "GET /show" do
    it "renders a successful response with custom fields" do
      client = create(:client, :with_custom_fields)
      get api_client_url(client)
      
      expect(response).to be_successful
      json = JSON.parse(response.body)
      expect(json["client"]).to be_present
      expect(json["custom_fields"]).to be_present
    end
  end
end
